# Generated by Django 6.0.3 on 2026-03-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baring.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baring.project')),
            ],
            options={
                'unique_together': {('employee', 'project')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='projects', through='baring.EmployeeProject', to='baring.employee'),
        ),
    ]
